// <auto-generated />
namespace Erenbook.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class a1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(a1));
        
        string IMigrationMetadata.Id
        {
            get { return "202202171303073_a1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
